version: "3.7"
services:
  db:
    image: mysql:latest
    container_name: ${DOCKER_PREFIX}-db
#    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: ${DOCKER_PREFIX}-cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
    networks:
      - app-network

  mailhog:
      image: mailhog/mailhog:latest
      container_name: ${DOCKER_PREFIX}-mailhog
      logging:
          driver: none
      ports:
          - ${MAILHOG_HTTP_PORT}:${MAILHOG_HTTP_PORT} #http port
          - ${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT} #smtp port
      networks:
        - app-network

  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_PREFIX}-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./${PROJECT_DIR_PATH}:/var/www/${PROJECT_DIR}
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  app:
    build:
      args:
        user: www
        uid: 1000
        PHP_VERSION: ${PHP_VERSION}
        PROJECT_DIR: ${PROJECT_DIR}
        NODE_VERSION: ${NODE_VERSION}
#      context: ./${PROJECT_DIR_PATH}
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - mailhog
      - nginx
      - cache
    image: laravel-image
    container_name: ${DOCKER_PREFIX}-app
    restart: unless-stopped
    working_dir: /var/www/${PROJECT_DIR}
    environment:
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      APP_NAME: ${APP_NAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: null
      MAIL_FROM_NAME: ""
      SESSION_SECURE_COOKIE: "false"
      SMTP_HOST: "smtp.mailtrap.io"
      SMTP_PORT: "465"
      SMTP_USE_AUTHENTICATION: "true"
      SMTP_SECURE_TRANSPORT: "TLS"
      SMTP_USERNAME: ${MAILTRAP_USERNAME}
      SMTP_PASSWORD: ${MAILTRAP_PASSWORD}
      SMTP_DEBUG: "false"
      HOST_HOSTNAME: ${HOSTNAME}
      VIRTUAL_HOST: "${PROJECT_DIR}.local"
      VIRTUAL_PORT: 3000
      REDIS_HOST: cache
      REDIS_PORT: 6379
    volumes:
      - ./${PROJECT_DIR_PATH}:/var/www/${PROJECT_DIR}
      - ./supervisord:/etc/supervisor/conf.d/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cache:
    driver: local
